### ISSUE TITLE
ENH: Remote Implementation

### ISSUE THREAD

**Issue by csmcallister** [GSA/tbm-scan#11]
As an ME analyst, I want the fbo scanner to be run automatically everyday with its results made available in a shared medium that anyone from my team can access at any time and so that we can identify TBM solicitations on fbo.gov and not worry about managing several versions of a spreadsheet when a single individual is running the scans manually and locally..
  
## Acceptance criteria
- [x] Figure out how to run crontab in D2D Python server. @jperez1725 
- [x] Figure out how to have project requirements `pip install`ed in Python server. @jperez1725 
- [x] Figure out if fbo's FTP url is whitelisted within Python server. If not, get it whitelisted. The FTP url is `ftp://ftp.fbo.gov/`. @jperez1725 
- [x] Submit IT tickets to have pyserver configured.
- [ ] Pyserver gets configured.
- [ ] Output is inserted in MS SQL database.
- [ ] Script still needs to be aware of past run dates in order to account for server issues.
- [ ] Logs need to be written to disk. 

NOTE: In the Python server, use `python3.6`

**Comment by jperez1725** [comment]
1. how to run crontab in D2D Python server. 
    Please open D2D Application Access SN ticket. 
    Select Python (under apps choice)
    Under "Additional Comments" say that you would like to create cron jobs
2. how to have project requirements pip installed in Python server
    Use SN D2D Deployment Request and tell us for package you are trying to upload
3. Figure out if fbo's FTP url is whitelisted within Python server. If not, get it whitelisted. The FTP url is ftp://ftp.fbo.gov/
    We don't allow FTP. It has to be SFT or ssh. Whould need to open firewall ticket to allow access to FBO

**Comment by jperez1725** [comment]
This is what we used for white-listing :
You need to click through to the Service Catalog in Service Now, and click on "View all Items" under Data Enterprise Services
Then click on GSA Proxy Request
Fill in the form and submit it. Include:
Orginating IP(s/range/CIDR block)
Destination URL(s)

**Comment by csmcallister** [comment]
IT tickets submitted today.
 - [RITM0638588](https://gsa.service-now.com/sp/?sys_id=51835d5edb363f003068fd0d0f96199c&view=sp&id=ticket&table=sc_req_item) - cron job permission
 - [RITM0638619](https://gsa.service-now.com/sp/?sys_id=21b8d9d6dbf63f003068fd0d0f96197f&view=sp&id=ticket&table=sc_req_item) - Python requirements installation request
 - [CHG0250488](https://gsa.service-now.com/sp/?id=form&table=change_request&filter=&sys_id=8d0c2592db727f003068fd0d0f9619d8&v=) - FBO FTP whitelist request

Update 7/24/19 @ 1:50pm
 - IT cancelled the first two tickets since they provided incomplete instructions (for RITM0638588) and since they didn't understand the request (for RITM0638619). I've resubmitted as REQ0462301 and REQ0462305, respectively.

**Comment by csmcallister** [comment]
IT approved the crontab usage and the python requirements on 7/26. Still waiting for the FTP whitelist.

FTP whitelist request has been escalate to ISSM.

**Comment by csmcallister** [comment]
GSAIT has suggested asking the FBO team if they can provide a more secure means to connect to the solicitation data (e.g. FTPS or SFTP). I submitted a ticket (190730-003858) to the Federal Service Desk today to ask that. Still waiting to hear from the ISSM if an exception can be made.

**Comment by csmcallister** [comment]
I submitted a second ticket (190730-004252) to the FBO team asking if they'd be willing to create an SFTP or FTPS server after they confirmed that there is only the FTP server available.

**Comment by csmcallister** [comment]
Heard from the ISSM on 8/28 that we will not be able to connect to the FTP, so I am closing this issue.
